let hangman = new Vue({
    el: "hangman-game",
    data: {
        alphabet = [
            "a",
            "b",
            "c",
            "d",
            "e",
            "f",
            "g",
            "h",
            "i",
            "j",
            "k",
            "l",
            "m",
            "n",
            "o",
            "p",
            "q",
            "r",
            "s",
            "t",
            "u",
            "v",
            "w",
            "x",
            "y",
            "z"
        ],
        possibleWords = [
            "Peter",
            "Simon",
            "Andrew",
            "James",
            "Zebedee",
            "John",
            "Philip",
            "Bartholomew",
            "Thomas",
            "Matthew",
            "James son of Alphaeus",
            "Thaddaeus",
            "Simon the Canaanite",
            "Judas Iscariot",
            "Apostle",
            "Mark",
            "Luke",
            "The Acts of the Apostles",
            "Pharisee",
            "Sadducee",
            "Temple",
            "New Testament",
            "Messiah",
            "Jesus of Nazareth",
            "Jerusalem",
            "Mary",
            "Joseph",
            "Stable",
            "Bethlehem",
            "Galilee",
            "Capernaum",
            "Samaria",
            "Widow of Nain",
            "Lazarus",
            "Mary Magdalene",
            "Martha",
            "He is Risen",
            "Golgotha"
        ],
    },
    methods: {
        reset() {
        
        },
        guessLetter() {
        
        },
    },
})
